name: Build Adaptation Packages

on:
  push:
    branches: [ "main", "trixie" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        device:
          - crownqltechn
          - starqltechn
          - star2qltechn

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y dpkg-dev devscripts build-essential fakeroot

      - name: Build package (${{ matrix.device }})
        run: |
          cd adaptation-samsung-${{ matrix.device }}

          dpkg-buildpackage -us -uc -b

      - name: Collect artifacts
        run: |
          mkdir -p packages/${{ matrix.device }}
          mv ../*.deb packages/${{ matrix.device }}/ || true

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: debian-packages-${{ matrix.device }}
          path: packages/${{ matrix.device }}/