name: Publish APT Repository

on:
  workflow_run:
    workflows: ["Build Adaptation Packages"]
    types:
      - completed

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: packages

      - name: Checkout repo repo
        uses: actions/checkout@v4
        with:
          repository: gdlukee/droidian-samsung_sdm845-repo
          token: ${{ secrets.GH_TOKEN }}
          path: repo

      - name: Copy packages
        run: |
          mkdir -p repo/packages
          cp -r packages/* repo/packages/

      - name: Generate Packages index
        run: |
          cd repo/packages

          for d in */; do
            dpkg-scanpackages "$d" /dev/null > "$d/Packages"
            gzip -kf "$d/Packages"
          done

      - name: Commit & push
        run: |
          cd repo
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add .
          git commit -m "Update packages" || true
          git push